/** ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : PE_LDD.h
**     Project     : Voice Prompt
**     Processor   : SKEAZ64MLH4
**     Version     : Component 01.013, Driver 01.00, CPU db: 3.00.000
**     Repository  : Kinetis
**     Compiler    : GNU C Compiler
**     Date/Time   : 2018-11-19, 16:51, # CodeGen: 83
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file PE_LDD.h                                                  
** @version 01.00
*/         
/*!
**  @addtogroup PE_LDD_module PE_LDD module documentation
**  @{
*/         
#ifndef __PE_LDD_H
#define __PE_LDD_H

/* MODULE PE_LDD. */

#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "Pins1.h"
#include "GREEN.h"
#include "BitIoLdd2.h"
#include "OUT_SDN.h"
#include "BitIoLdd5.h"
#include "BTN0.h"
#include "BitIoLdd4.h"
#include "BTN1.h"
#include "BitIoLdd3.h"
#include "OUT_DATA1.h"
#include "BitIoLdd7.h"
#include "INT_1MS.h"
#include "TimerIntLdd1.h"
#include "FTM0.h"
#include "Delay_100us.h"
#include "TimerIntLdd2.h"
#include "FTM1.h"
#include "OUT_BUSY.h"
#include "BitIoLdd16.h"
#include "OUT_RST.h"
#include "BitIoLdd17.h"
#include "TJA1040_STB.h"
#include "BitIoLdd18.h"
#include "BCM_sig.h"
#include "BitIoLdd9.h"
#include "CAN.h"
#include "BlueTooth.h"
#include "ASerialLdd1.h"
#include "TJA1028_EN.h"
#include "BitIoLdd12.h"
#include "LIN.h"
#include "ASerialLdd2.h"
#include "Flash_C.h"
#include "BitIoLdd13.h"
#include "LED_GREEN.h"
#include "BitIoLdd14.h"
#include "LED_RED.h"
#include "BitIoLdd15.h"
#include "BEEP.h"
#include "BitIoLdd19.h"
#include "MOTOR.h"
#include "BitIoLdd20.h"
#include "IN_SDN.h"
#include "BitIoLdd1.h"
#include "IN_DATA1.h"
#include "BitIoLdd6.h"
#include "IN_BUSY.h"
#include "BitIoLdd21.h"
#include "IN_RST.h"
#include "BitIoLdd22.h"
#include "LIGHT_BAR.h"
#include "BitsIoLdd1.h"


/*
** ===================================================================
** Function prototypes
** ===================================================================
*/

/*
** ===================================================================
**     Method      :  Cpu_PE_FillMemory (component SKEAZ128LH4)
*/
/*!
**     @brief
**         Fills a memory area block by a specified value.
**     @param
**       SourceAddressPtr - Source address pointer.
**     @param
**       c - A value used to fill a memory block.
**     @param
**       len - Length of a memory block to fill.
*/
/* ===================================================================*/
void PE_FillMemory(register void* SourceAddressPtr, register uint8_t c, register uint32_t len);

/*
** ===================================================================
**     Method      :  Cpu_PE_PeripheralUsed (component SKEAZ128LH4)
*/
/*!
**     @brief
**         Returns information whether a peripheral is allocated by PEx 
**         or not.
**     @param
**       PrphBaseAddress - Base address of a peripheral.
**     @return
**       TRUE if a peripheral is used by PEx or FALSE if it isn't used.
*/
/* ===================================================================*/
bool PE_PeripheralUsed(uint32_t PrphBaseAddress);

/*
** ===================================================================
**     Method      :  Cpu_LDD_SetClockConfiguration (component SKEAZ128LH4)
*/
/*!
**     @brief
**         Changes the clock configuration of all LDD components in a 
**         project.
**     @param
**       ClockConfiguration - New CPU clock configuration changed by CPU SetClockConfiguration method.
*/
/* ===================================================================*/
void LDD_SetClockConfiguration(LDD_TClockConfiguration ClockConfiguration);

/* END PE_LDD. */


#endif

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
